# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Hero name in Dota 2.', max_length=50, unique=True, verbose_name='Hero Name')),
                ('photo', models.ImageField(help_text='Hero picture.', upload_to='')),
                ('category', models.CharField(choices=[('strength', 'Strength hero'), ('agility', 'Agility hero'), ('intelligence', 'Intelligence hero')], help_text='Specify hero category from choices, i.e Strength.', max_length=25)),
                ('attack_type', models.CharField(choices=[('malee', 'Malee attack'), ('ranged', 'Ranged attack')], help_text='Specify hero attack type from choices, i.e. Malee.', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.FloatField(help_text='Advantage in percentage against opponent hero.')),
                ('win_rate', models.FloatField(help_text='Game win rate in percentage.')),
                ('matches_played', models.PositiveIntegerField(default=0, help_text='Total games played')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heros.Hero')),
                ('opponent_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponents', to='heros.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='HeroRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('complexity', 'Complexity'), ('carry', 'Carry'), ('support', 'Support'), ('nuker', 'Nuker'), ('disabler', 'Disabler'), ('jungler', 'Jungler'), ('durable', 'Durable'), ('escape', 'Escape'), ('pusher', 'Pusher'), ('initiator', 'Initiator'), ('roamer', 'Roamer')], help_text='Hero role name, e.g. Carry, Support, Jungler', max_length=50, verbose_name='Hero role name')),
                ('level', models.CharField(choices=[(1, 'Basic level role'), (2, 'Average level role'), (3, 'Excellent level role')], help_text='Specify level for the hero role, i.e Average Malee.', max_length=25)),
                ('win_rate', models.FloatField(blank=True, help_text='Game win rate in percentage for this role.', null=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_roles', to='heros.Hero')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='herorole',
            unique_together=set([('hero', 'role')]),
        ),
    ]
