# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='attack_type',
            field=models.CharField(choices=[('melee', 'Melee attack'), ('ranged', 'Ranged attack')], help_text='Specify hero attack type from choices, i.e. Melee.', max_length=25),
        ),
        migrations.AlterField(
            model_name='herorole',
            name='role',
            field=models.CharField(choices=[('carry', 'Carry'), ('support', 'Support'), ('nuker', 'Nuker'), ('disabler', 'Disabler'), ('jungler', 'Jungler'), ('durable', 'Durable'), ('escape', 'Escape'), ('pusher', 'Pusher'), ('initiator', 'Initiator'), ('roamer', 'Roamer')], help_text='Hero role name, e.g. Carry, Support, Jungler', max_length=50, verbose_name='Hero role name'),
        ),
    ]
